# Copyright lol

OrdererOrgs:
  - Name: Orderer
    Domain: example.com
    Specs:
      - Hostname: orderer

PeerOrgs:
  - Name: MEDSOS
    Domain: MEDSOS.example.com
    EnableNodeOUs: true
    Template:
      Count: 2
    Users:
      Count: 0
  - Name: BFF
    Domain: BFF.example.com
    EnableNodeOUs: true
    Template:
      Count: 2
    Users:
      Count: 0
  - Name: BLUECITY
    Domain: BLUECITY.example.com
    EnableNodeOUs: true
    Template:
      Count: 2
    Users:
      Count: 0
